[build]
  publish = "."

[[redirects]]
  from = "/owner/*"
  to = "/frontend/dist/index.html"
  status = 200

[[redirects]]  
  from = "/agency/*"
  to = "/frontend-agency/dist/index.html"
  status = 200

[[redirects]]
  from = "/customer/*"
  to = "/frontend-customer/dist/index.html"
  status = 200
